In [10]:
import numpy as np
import pandas as pd
from pulp import *
import copy

In [48]:
data = pd.read_csv('dataset.csv')
data = data.sort_values(by = 'Unnamed: 0')
ids = data[['Unnamed: 0']]
data = data.drop('Unnamed: 0', axis = 'columns')
data = data.reset_index(drop = True)
data.index = 'a'+ data.index.astype('str')
data

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt
a0,3,840000.0,13.8,3.0,2.0,2.0,534.0,136.00,1965.0
a1,4,1100000.0,5.9,4.0,2.0,5.0,559.0,195.00,1920.0
a2,2,495000.0,13.9,2.0,1.0,1.0,76.0,79.00,1980.0
a3,3,1120000.0,7.8,3.0,2.0,1.0,293.0,180.00,2006.0
a4,4,2325000.0,9.2,4.0,3.0,2.0,638.0,314.00,1930.0
a5,3,822000.0,13.0,3.0,1.0,4.0,700.0,105.00,1950.0
a6,3,1560000.0,4.6,3.0,2.0,0.0,198.0,148.00,1910.0
a7,2,650000.0,10.5,2.0,1.0,3.0,620.0,85.00,1950.0
a8,3,1223500.0,7.9,3.0,2.0,2.0,721.0,136.00,1980.0
a9,2,790000.0,11.2,2.0,1.0,2.0,196.0,109.00,1970.0
a10,1,440000.0,2.8,1.0,1.0,1.0,0.0,65.00,1920.0
a11,3,923000.0,8.4,3.0,1.0,0.0,221.0,118.00,1900.0
a12,2,1265000.0,2.6,2.0,1.0,0.0,70.0,102.00,1890.0
a13,2,880000.0,3.8,2.0,1.0,2.0,163.0,83.00,1980.0
a14,3,950000.0,3.8,3.0,2.0,2.0,0.0,134.00,2012.0
a15,2,479000.0,2.6,2.0,1.0,1.0,0.0,62.00,1970.0
a16,4,2200000.0,11.2,4.0,2.0,2.0,734.0,272.00,1920.0
a17,4,2440000.0,8.0,4.0,3.0,3.0,500.0,278.00,2005.0
a18,3,1225000.0,8.9,3.0,1.0,1.0,311.0,126.00,1920.0
a19,2,600000.0,5.1,2.0,1.0,1.0,1452.0,96.00,1970.0
a20,3,720000.0,9.5,3.0,2.0,1.0,231.0,145.00,2012.0
a21,3,625000.0,12.4,3.0,1.0,2.0,585.0,88.00,1960.0
a22,3,1035000.0,7.8,3.0,2.0,2.0,275.0,145.00,1920.0
a23,4,1180000.0,14.0,4.0,1.0,2.0,604.0,183.00,1965.0
a24,2,420000.0,9.1,2.0,1.0,1.0,78.0,130.00,1980.0
a25,5,1900000.0,10.7,5.0,3.0,2.0,583.0,271.00,2009.0
a26,6,1455000.0,7.8,6.0,3.0,4.0,768.0,285.00,1997.0
a27,1,365000.0,7.4,1.0,1.0,1.0,0.0,46.00,1960.0
a28,3,1300000.0,5.5,3.0,1.0,0.0,191.0,108.00,1915.0
a29,3,1190000.0,8.8,3.0,2.0,2.0,572.0,118.00,1935.0
a30,3,680000.0,2.1,3.0,2.0,2.0,0.0,110.87,2003.0
a31,4,521000.0,45.9,4.0,2.0,2.0,978.0,144.00,1980.0
a32,2,645000.0,16.0,2.0,1.0,1.0,105.0,64.00,1970.0
a33,3,1175000.0,10.5,3.0,1.0,3.0,284.0,120.00,1970.0
a34,3,600000.0,14.8,3.0,1.0,3.0,406.0,196.00,2005.0
a35,2,1100000.0,16.7,2.0,1.0,1.0,258.0,106.00,1980.0
a36,4,732000.0,17.9,3.0,2.0,1.0,808.0,184.00,1980.0
a37,3,877000.0,17.9,3.0,1.0,2.0,533.0,135.00,1965.0
a38,3,860000.0,23.5,3.0,2.0,2.0,537.0,220.00,2001.0
a39,4,870000.0,14.8,4.0,2.0,2.0,463.0,307.00,2012.0
a40,3,815000.0,16.1,3.0,2.0,2.0,609.0,168.00,1980.0
a41,4,1350000.0,5.2,4.0,2.0,1.0,372.0,184.00,1920.0
a42,1,361000.0,7.8,1.0,1.0,1.0,60.0,53.00,1975.0
a43,3,828000.0,14.3,3.0,2.0,2.0,301.0,117.00,1980.0
a44,3,485000.0,20.6,3.0,2.0,1.0,321.0,150.00,2013.0
a45,3,1307500.0,7.3,3.0,1.0,1.0,316.0,111.00,1940.0
a46,2,653000.0,10.9,2.0,1.0,1.0,84.0,77.00,1970.0
a47,2,1300000.0,2.1,2.0,1.0,1.0,125.0,124.00,2000.0
a48,4,1450000.0,15.5,4.0,2.0,2.0,771.0,196.00,1970.0
a49,3,1400000.0,10.1,3.0,2.0,3.0,818.0,193.00,2011.0

In [41]:
ids

    Unnamed: 0
0         9084
1         3833
2         8817
3         9047
4         8257
5         6594
6         9838
7         6124
8        11048
9         7588
10         800
11       10957
12       13176
13        3249
14        7343
15         318
16       11298
17       13260
18       10808
19       12791
20        8163
21        6562
22       12946
23       12983
24        3177
25        4793
26        4236
27       13390
28        8361
29        9236
30        9165
31        2757
32        4583
33        6902
34        1984
35        3404
36        6551
37         171
38       11314
39        6758
40        8059
41        2874
42        5273
43        7764
44        4000
45       13118
46        8840
47        4744
48        7100
49        7388

In [3]:
data.describe()

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt
count,50.000000,5.000000e+01,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000,50.000000
mean,2.940000,1.010540e+06,10.760000,2.920000,1.580000,1.72000,400.440000,146.037400,1966.520000
std,0.977502,4.836915e+05,7.117727,0.965528,0.641745,1.03095,305.460586,67.062725,33.749522
min,1.000000,3.610000e+05,2.100000,1.000000,1.000000,0.00000,0.000000,46.000000,1890.000000
25%,2.000000,6.507500e+05,7.325000,2.000000,1.000000,1.00000,170.000000,105.250000,1942.500000
50%,3.000000,8.785000e+05,9.350000,3.000000,1.500000,2.00000,318.500000,132.000000,1970.000000
75%,3.000000,1.255000e+06,13.975000,3.000000,2.000000,2.00000,599.250000,183.750000,1992.750000
max,6.000000,2.440000e+06,45.900000,6.000000,3.000000,5.00000,1452.000000,314.000000,2013.000000

## **1. UTA algorithm - finding minimal subset of inconsistent constraints** ##

In [4]:
# preference_list - list of pairs (better, worse)
preference_list = [("a4", "a9"), ("a9", "a13"), ("a13", "a4"), ("a4", "a1"), ("a32", "a45"), 
("a27", "a18"), ("a25", "a28"), ("a45", "a50"), ("a43", "a37"), ("a39", "a38"), 
("a27", "a18"), ("a31", "a33"), ("a30", "a42"), ("a40", "a35"), ("a27", "a26"),
("a3", "a11"), ("a6", "a7")]

In [6]:
# criteria_types - list of pairs in form (gain or cost type, is discrete?)
criteria_types = [('gain', True), ('cost', False), 
('cost', False), ('gain', True), ('gain', True), 
('gain', True), ('gain', False), ('gain', False), 
('gain', False)]

In [ ]:
# def distribute_breakpoints(min, max, number_of_breakpoints, type_of_cr):
#     cost_or_gain, is_discrete = type_of_cr

In [ ]:
# def interpolate(u_vals, score, bp)

In [ ]:
def build_uta_model(preference_list, df, criteria_types):
    # 0. Define Linear Problem - we want to minimize number of const that are excluded
    model = LpProblem('uta_model', LpMinimize)
    eps = 0.001

    pairwise_comparisons = copy.deepcopy(preference_list)
    binary_variables = LpVariable.dicts('bin_var', pairwise_comparisons, cat='Binary')
    model += lpSum(list(binary_variables.values()))

    # 1. Add weights const
    weights = []
    for crit in df.columns:
        weights.append(LpVariable(f'w_{crit}', lowBound = 1/(5*len(df.columns)), upBound = 0.5, cat = 'Continuous'))

    # 2. Add norm const
    model += lpSum(weights) == 1

    # 3. Utility constraints
    utility_vars = {}
    for alt in df.index:
        for criterion in df.columns:
            curr_util_name = 'u_'+alt+'_'+criterion
            utility_vars[curr_util_name] = LpVariable(curr_util_name, lowBound=0, cat = 'Continuous')
    
    for i in range(len(criteria_types)):
        # Find best and worst
        if criteria_types[i][0] == 'cost':
            best_idx = np.argmin(df[df.columns[i]])
            worst_idx = np.argmax(df[df.columns[i]])
        else:
            worst_idx = np.argmin(df[df.columns[i]])
            best_idx = np.argmax(df[df.columns[i]])

        model += utility_vars[f'u_{df.index[best_idx]}_{df.columns[i]}'] == 1
        model += utility_vars[f'u_{df.index[worst_idx]}_{df.columns[i]}'] == 0

        # Monocity constraint
        if criteria_types[i][0] == 'cost':
            sorted_alts = np.argsort(df[df.columns[i]])
        else:
            sorted_alts = np.argsort(df[df.columns[i]])[::-1]
        for j in range(len(sorted_alts)-1):
                model += utility_vars[f'u_{df.index[sorted_alts[j]]}_{df.columns[i]}'] >= utility_vars[f'u_{df.index[sorted_alts[j+1]]}_{df.columns[i]}']
    print(model)

    # 4. Add utility functions
    for better, worse in pairwise_comparisons:
        # if criterion can't be met, then 1 is substracted on the right side so that it holds
        model += lpSum([...]) > lpSum(...) - binary_vars[(alt1, alt2)] + eps

    return model

In [52]:
build_uta_model(preference_list, data, criteria_types)

uta_model:
MINIMIZE
1*bin_var_('a13',_'a4') + 1*bin_var_('a25',_'a28') + 1*bin_var_('a27',_'a18') + 1*bin_var_('a27',_'a26') + 1*bin_var_('a3',_'a11') + 1*bin_var_('a30',_'a42') + 1*bin_var_('a31',_'a33') + 1*bin_var_('a32',_'a45') + 1*bin_var_('a39',_'a38') + 1*bin_var_('a4',_'a1') + 1*bin_var_('a4',_'a9') + 1*bin_var_('a40',_'a35') + 1*bin_var_('a43',_'a37') + 1*bin_var_('a45',_'a50') + 1*bin_var_('a6',_'a7') + 1*bin_var_('a9',_'a13') + 0
SUBJECT TO
_C1: w_Bathroom + w_Bedroom2 + w_BuildingArea + w_Car + w_Distance
 + w_Landsize + w_Price + w_Rooms + w_YearBuilt = 1

VARIABLES
0 <= bin_var_('a13',_'a4') <= 1 Integer
0 <= bin_var_('a25',_'a28') <= 1 Integer
0 <= bin_var_('a27',_'a18') <= 1 Integer
0 <= bin_var_('a27',_'a26') <= 1 Integer
0 <= bin_var_('a3',_'a11') <= 1 Integer
0 <= bin_var_('a30',_'a42') <= 1 Integer
0 <= bin_var_('a31',_'a33') <= 1 Integer
0 <= bin_var_('a32',_'a45') <= 1 Integer
0 <= bin_var_('a39',_'a38') <= 1 Integer
0 <= bin_var_('a4',_'a1') <= 1 Integer
0 <= bin_var_('a4',_'a9') <= 1 Integer
0 <= bin_var_('a40',_'a35') <= 1 Integer
0 <= bin_var_('a43',_'a37') <= 1 Integer
0 <= bin_var_('a45',_'a50') <= 1 Integer
0 <= bin_var_('a6',_'a7') <= 1 Integer
0 <= bin_var_('a9',_'a13') <= 1 Integer
0.0222222222222 <= w_Bathroom <= 0.5 Continuous
0.0222222222222 <= w_Bedroom2 <= 0.5 Continuous
0.0222222222222 <= w_BuildingArea <= 0.5 Continuous
0.0222222222222 <= w_Car <= 0.5 Continuous
0.0222222222222 <= w_Distance <= 0.5 Continuous
0.0222222222222 <= w_Landsize <= 0.5 Continuous
0.0222222222222 <= w_Price <= 0.5 Continuous
0.0222222222222 <= w_Rooms <= 0.5 Continuous
0.0222222222222 <= w_YearBuilt <= 0.5 Continuous

uta_model:
MINIMIZE
1*bin_var_('a13',_'a4') + 1*bin_var_('a25',_'a28') + 1*bin_var_('a27',_'a18') + 1*bin_var_('a27',_'a26') + 1*bin_var_('a3',_'a11') + 1*bin_var_('a30',_'a42') + 1*bin_var_('a31',_'a33') + 1*bin_var_('a32',_'a45') + 1*bin_var_('a39',_'a38') + 1*bin_var_('a4',_'a1') + 1*bin_var_('a4',_'a9') + 1*bin_var_('a40',_'a35') + 1*bin_var_('a43',_'a37') + 1*bin_var_('a45',_'a50') + 1*bin_var_('a6',_'a7') + 1*bin_var_('a9',_'a13') + 0
SUBJECT TO
_C1: w_Bathroom + w_Bedroom2 + w_BuildingArea + w_Car + w_Distance
 + w_Landsize + w_Price + w_Rooms + w_YearBuilt = 1

_C2: u_a26_Rooms = 1

_C3: u_a10_Rooms = 0

_C4: - u_a25_Rooms + u_a26_Rooms >= 0

_C5: - u_a1_Rooms + u_a25_Rooms >= 0

_C6: u_a1_Rooms - u_a48_Rooms >= 0

_C7: u_a48_Rooms - u_a4_Rooms >= 0

_C8: - u_a23_Rooms + u_a4_Rooms >= 0

_C9: u_a23_Rooms - u_a31_Rooms >= 0

_C10: u_a31_Rooms - u_a41_Rooms >= 0

_C11: - u_a39_Rooms + u_a41_Rooms >= 0

_C12: - u_a16_Rooms + u_a39_Rooms >= 0

_C13: u_a16_Rooms - u_a36_Rooms >= 0

_C14: - u_a17_Rooms + u_a36_Rooms >= 0

_C15: u_a17_Rooms - u_a20_Rooms >= 0

_C16: u_a20_Rooms - u_a22_Rooms >= 0

_C17: - u_a21_Rooms + u_a22_Rooms >= 0

_C18: u_a21_Rooms - u_a49_Rooms >= 0

_C19: - u_a18_Rooms + u_a49_Rooms >= 0

_C20: - u_a11_Rooms + u_a18_Rooms >= 0

_C21: u_a11_Rooms - u_a8_Rooms >= 0

_C22: - u_a6_Rooms + u_a8_Rooms >= 0

_C23: - u_a5_Rooms + u_a6_Rooms >= 0

_C24: - u_a3_Rooms + u_a5_Rooms >= 0

_C25: - u_a14_Rooms + u_a3_Rooms >= 0

_C26: - u_a0_Rooms + u_a14_Rooms >= 0

_C27: u_a0_Rooms - u_a29_Rooms >= 0

_C28: u_a29_Rooms - u_a30_Rooms >= 0

_C29: u_a30_Rooms - u_a33_Rooms >= 0

_C30: u_a33_Rooms - u_a34_Rooms >= 0

_C31: u_a34_Rooms - u_a37_Rooms >= 0

_C32: u_a37_Rooms - u_a45_Rooms >= 0

_C33: - u_a38_Rooms + u_a45_Rooms >= 0

_C34: u_a38_Rooms - u_a44_Rooms >= 0

_C35: - u_a28_Rooms + u_a44_Rooms >= 0

_C36: u_a28_Rooms - u_a40_Rooms >= 0

_C37: u_a40_Rooms - u_a43_Rooms >= 0

_C38: - u_a12_Rooms + u_a43_Rooms >= 0

_C39: u_a12_Rooms - u_a7_Rooms >= 0

_C40: - u_a47_Rooms + u_a7_Rooms >= 0

_C41: - u_a2_Rooms + u_a47_Rooms >= 0

_C42: u_a2_Rooms - u_a46_Rooms >= 0

_C43: - u_a24_Rooms + u_a46_Rooms >= 0

_C44: u_a24_Rooms - u_a9_Rooms >= 0

_C45: - u_a13_Rooms + u_a9_Rooms >= 0

_C46: u_a13_Rooms - u_a15_Rooms >= 0

_C47: u_a15_Rooms - u_a35_Rooms >= 0

_C48: - u_a19_Rooms + u_a35_Rooms >= 0

_C49: u_a19_Rooms - u_a32_Rooms >= 0

_C50: u_a32_Rooms - u_a42_Rooms >= 0

_C51: - u_a10_Rooms + u_a42_Rooms >= 0

_C52: u_a10_Rooms - u_a27_Rooms >= 0

_C53: u_a42_Price = 1

_C54: u_a17_Price = 0

_C55: - u_a27_Price + u_a42_Price >= 0

_C56: - u_a24_Price + u_a27_Price >= 0

_C57: - u_a10_Price + u_a24_Price >= 0

_C58: u_a10_Price - u_a15_Price >= 0

_C59: u_a15_Price - u_a44_Price >= 0

_C60: - u_a2_Price + u_a44_Price >= 0

_C61: u_a2_Price - u_a31_Price >= 0

_C62: u_a31_Price - u_a34_Price >= 0

_C63: - u_a19_Price + u_a34_Price >= 0

_C64: u_a19_Price - u_a21_Price >= 0

_C65: u_a21_Price - u_a32_Price >= 0

_C66: u_a32_Price - u_a7_Price >= 0

_C67: - u_a46_Price + u_a7_Price >= 0

_C68: - u_a30_Price + u_a46_Price >= 0

_C69: - u_a20_Price + u_a30_Price >= 0

_C70: u_a20_Price - u_a36_Price >= 0

_C71: u_a36_Price - u_a9_Price >= 0

_C72: - u_a40_Price + u_a9_Price >= 0

_C73: u_a40_Price - u_a5_Price >= 0

_C74: - u_a43_Price + u_a5_Price >= 0

_C75: - u_a0_Price + u_a43_Price >= 0

_C76: u_a0_Price - u_a38_Price >= 0

_C77: u_a38_Price - u_a39_Price >= 0

_C78: - u_a37_Price + u_a39_Price >= 0

_C79: - u_a13_Price + u_a37_Price >= 0

_C80: - u_a11_Price + u_a13_Price >= 0

_C81: u_a11_Price - u_a14_Price >= 0

_C82: u_a14_Price - u_a22_Price >= 0

_C83: - u_a1_Price + u_a22_Price >= 0

_C84: u_a1_Price - u_a35_Price >= 0

_C85: u_a35_Price - u_a3_Price >= 0

_C86: - u_a33_Price + u_a3_Price >= 0

_C87: - u_a23_Price + u_a33_Price >= 0

_C88: u_a23_Price - u_a29_Price >= 0

_C89: u_a29_Price - u_a8_Price >= 0

_C90: - u_a18_Price + u_a8_Price >= 0

_C91: - u_a12_Price + u_a18_Price >= 0

_C92: u_a12_Price - u_a28_Price >= 0

_C93: u_a28_Price - u_a47_Price >= 0

_C94: - u_a45_Price + u_a47_Price >= 0

_C95: - u_a41_Price + u_a45_Price >= 0

_C96: u_a41_Price - u_a49_Price >= 0

_C97: - u_a48_Price + u_a49_Price >= 0

_C98: - u_a26_Price + u_a48_Price >= 0

_C99: u_a26_Price - u_a6_Price >= 0

_C100: - u_a25_Price + u_a6_Price >= 0

_C101: - u_a16_Price + u_a25_Price >= 0

_C102: u_a16_Price - u_a4_Price >= 0

_C103: - u_a17_Price + u_a4_Price >= 0

_C104: u_a30_Distance = 1

_C105: u_a31_Distance = 0

_C106: - u_a30_Distance + u_a47_Distance >= 0

_C107: - u_a12_Distance + u_a30_Distance >= 0

_C108: u_a12_Distance - u_a15_Distance >= 0

_C109: - u_a10_Distance + u_a15_Distance >= 0

_C110: u_a10_Distance - u_a13_Distance >= 0

_C111: u_a13_Distance - u_a14_Distance >= 0

_C112: u_a14_Distance - u_a6_Distance >= 0

_C113: - u_a19_Distance + u_a6_Distance >= 0

_C114: u_a19_Distance - u_a41_Distance >= 0

_C115: - u_a28_Distance + u_a41_Distance >= 0

_C116: - u_a1_Distance + u_a28_Distance >= 0

_C117: u_a1_Distance - u_a45_Distance >= 0

_C118: - u_a27_Distance + u_a45_Distance >= 0

_C119: - u_a22_Distance + u_a27_Distance >= 0

_C120: u_a22_Distance - u_a26_Distance >= 0

_C121: u_a26_Distance - u_a42_Distance >= 0

_C122: - u_a3_Distance + u_a42_Distance >= 0

_C123: u_a3_Distance - u_a8_Distance >= 0

_C124: - u_a17_Distance + u_a8_Distance >= 0

_C125: - u_a11_Distance + u_a17_Distance >= 0

_C126: u_a11_Distance - u_a29_Distance >= 0

_C127: - u_a18_Distance + u_a29_Distance >= 0

_C128: u_a18_Distance - u_a24_Distance >= 0

_C129: u_a24_Distance - u_a4_Distance >= 0

_C130: - u_a20_Distance + u_a4_Distance >= 0

_C131: u_a20_Distance - u_a49_Distance >= 0

_C132: - u_a33_Distance + u_a49_Distance >= 0

_C133: u_a33_Distance - u_a7_Distance >= 0

_C134: - u_a25_Distance + u_a7_Distance >= 0

_C135: u_a25_Distance - u_a46_Distance >= 0

_C136: - u_a16_Distance + u_a46_Distance >= 0

_C137: u_a16_Distance - u_a9_Distance >= 0

_C138: - u_a21_Distance + u_a9_Distance >= 0

_C139: u_a21_Distance - u_a5_Distance >= 0

_C140: - u_a0_Distance + u_a5_Distance >= 0

_C141: u_a0_Distance - u_a2_Distance >= 0

_C142: - u_a23_Distance + u_a2_Distance >= 0

_C143: u_a23_Distance - u_a43_Distance >= 0

_C144: - u_a34_Distance + u_a43_Distance >= 0

_C145: u_a34_Distance - u_a39_Distance >= 0

_C146: u_a39_Distance - u_a48_Distance >= 0

_C147: - u_a32_Distance + u_a48_Distance >= 0

_C148: u_a32_Distance - u_a40_Distance >= 0

_C149: - u_a35_Distance + u_a40_Distance >= 0

_C150: u_a35_Distance - u_a37_Distance >= 0

_C151: - u_a36_Distance + u_a37_Distance >= 0

_C152: u_a36_Distance - u_a44_Distance >= 0

_C153: - u_a38_Distance + u_a44_Distance >= 0

_C154: - u_a31_Distance + u_a38_Distance >= 0

_C155: u_a26_Bedroom2 = 1

_C156: u_a10_Bedroom2 = 0

_C157: - u_a25_Bedroom2 + u_a26_Bedroom2 >= 0

_C158: - u_a1_Bedroom2 + u_a25_Bedroom2 >= 0

_C159: u_a1_Bedroom2 - u_a48_Bedroom2 >= 0

_C160: u_a48_Bedroom2 - u_a4_Bedroom2 >= 0

_C161: - u_a23_Bedroom2 + u_a4_Bedroom2 >= 0

_C162: u_a23_Bedroom2 - u_a31_Bedroom2 >= 0

_C163: u_a31_Bedroom2 - u_a41_Bedroom2 >= 0

_C164: - u_a39_Bedroom2 + u_a41_Bedroom2 >= 0

_C165: - u_a16_Bedroom2 + u_a39_Bedroom2 >= 0

_C166: u_a16_Bedroom2 - u_a17_Bedroom2 >= 0

_C167: u_a17_Bedroom2 - u_a20_Bedroom2 >= 0

_C168: u_a20_Bedroom2 - u_a22_Bedroom2 >= 0

_C169: - u_a21_Bedroom2 + u_a22_Bedroom2 >= 0

_C170: u_a21_Bedroom2 - u_a49_Bedroom2 >= 0

_C171: - u_a18_Bedroom2 + u_a49_Bedroom2 >= 0

_C172: - u_a11_Bedroom2 + u_a18_Bedroom2 >= 0

_C173: u_a11_Bedroom2 - u_a8_Bedroom2 >= 0

_C174: - u_a6_Bedroom2 + u_a8_Bedroom2 >= 0

_C175: - u_a5_Bedroom2 + u_a6_Bedroom2 >= 0

_C176: - u_a3_Bedroom2 + u_a5_Bedroom2 >= 0

_C177: - u_a14_Bedroom2 + u_a3_Bedroom2 >= 0

_C178: - u_a0_Bedroom2 + u_a14_Bedroom2 >= 0

_C179: u_a0_Bedroom2 - u_a43_Bedroom2 >= 0

_C180: - u_a38_Bedroom2 + u_a43_Bedroom2 >= 0

_C181: - u_a29_Bedroom2 + u_a38_Bedroom2 >= 0

_C182: u_a29_Bedroom2 - u_a30_Bedroom2 >= 0

_C183: u_a30_Bedroom2 - u_a40_Bedroom2 >= 0

_C184: - u_a33_Bedroom2 + u_a40_Bedroom2 >= 0

_C185: u_a33_Bedroom2 - u_a34_Bedroom2 >= 0

_C186: u_a34_Bedroom2 - u_a44_Bedroom2 >= 0

_C187: - u_a28_Bedroom2 + u_a44_Bedroom2 >= 0

_C188: u_a28_Bedroom2 - u_a36_Bedroom2 >= 0

_C189: u_a36_Bedroom2 - u_a37_Bedroom2 >= 0

_C190: u_a37_Bedroom2 - u_a45_Bedroom2 >= 0

_C191: - u_a13_Bedroom2 + u_a45_Bedroom2 >= 0

_C192: u_a13_Bedroom2 - u_a7_Bedroom2 >= 0

_C193: - u_a2_Bedroom2 + u_a7_Bedroom2 >= 0

_C194: u_a2_Bedroom2 - u_a47_Bedroom2 >= 0

_C195: - u_a46_Bedroom2 + u_a47_Bedroom2 >= 0

_C196: - u_a24_Bedroom2 + u_a46_Bedroom2 >= 0

_C197: u_a24_Bedroom2 - u_a9_Bedroom2 >= 0

_C198: - u_a12_Bedroom2 + u_a9_Bedroom2 >= 0

_C199: u_a12_Bedroom2 - u_a15_Bedroom2 >= 0

_C200: u_a15_Bedroom2 - u_a35_Bedroom2 >= 0

_C201: - u_a19_Bedroom2 + u_a35_Bedroom2 >= 0

_C202: u_a19_Bedroom2 - u_a32_Bedroom2 >= 0

_C203: u_a32_Bedroom2 - u_a42_Bedroom2 >= 0

_C204: - u_a10_Bedroom2 + u_a42_Bedroom2 >= 0

_C205: u_a10_Bedroom2 - u_a27_Bedroom2 >= 0

_C206: u_a4_Bathroom = 1

_C207: u_a2_Bathroom = 0

_C208: u_a17_Bathroom - u_a26_Bathroom >= 0

_C209: u_a26_Bathroom - u_a4_Bathroom >= 0

_C210: - u_a25_Bathroom + u_a4_Bathroom >= 0

_C211: u_a25_Bathroom - u_a49_Bathroom >= 0

_C212: - u_a29_Bathroom + u_a49_Bathroom >= 0

_C213: u_a29_Bathroom - u_a48_Bathroom >= 0

_C214: - u_a22_Bathroom + u_a48_Bathroom >= 0

_C215: - u_a20_Bathroom + u_a22_Bathroom >= 0

_C216: - u_a16_Bathroom + u_a20_Bathroom >= 0

_C217: u_a16_Bathroom - u_a31_Bathroom >= 0

_C218: - u_a14_Bathroom + u_a31_Bathroom >= 0

_C219: u_a14_Bathroom - u_a8_Bathroom >= 0

_C220: - u_a6_Bathroom + u_a8_Bathroom >= 0

_C221: - u_a3_Bathroom + u_a6_Bathroom >= 0

_C222: - u_a1_Bathroom + u_a3_Bathroom >= 0

_C223: u_a1_Bathroom - u_a30_Bathroom >= 0

_C224: - u_a0_Bathroom + u_a30_Bathroom >= 0

_C225: u_a0_Bathroom - u_a38_Bathroom >= 0

_C226: u_a38_Bathroom - u_a41_Bathroom >= 0

_C227: - u_a40_Bathroom + u_a41_Bathroom >= 0

_C228: - u_a36_Bathroom + u_a40_Bathroom >= 0

_C229: u_a36_Bathroom - u_a43_Bathroom >= 0

_C230: u_a43_Bathroom - u_a44_Bathroom >= 0

_C231: - u_a39_Bathroom + u_a44_Bathroom >= 0

_C232: u_a39_Bathroom - u_a7_Bathroom >= 0

_C233: - u_a10_Bathroom + u_a7_Bathroom >= 0

_C234: u_a10_Bathroom - u_a9_Bathroom >= 0

_C235: - u_a32_Bathroom + u_a9_Bathroom >= 0

_C236: - u_a12_Bathroom + u_a32_Bathroom >= 0

_C237: u_a12_Bathroom - u_a5_Bathroom >= 0

_C238: - u_a45_Bathroom + u_a5_Bathroom >= 0

_C239: u_a45_Bathroom - u_a46_Bathroom >= 0

_C240: - u_a2_Bathroom + u_a46_Bathroom >= 0

_C241: u_a2_Bathroom - u_a47_Bathroom >= 0

_C242: - u_a11_Bathroom + u_a47_Bathroom >= 0

_C243: u_a11_Bathroom - u_a15_Bathroom >= 0

_C244: - u_a13_Bathroom + u_a15_Bathroom >= 0

_C245: u_a13_Bathroom - u_a42_Bathroom >= 0

_C246: - u_a33_Bathroom + u_a42_Bathroom >= 0

_C247: - u_a18_Bathroom + u_a33_Bathroom >= 0

_C248: u_a18_Bathroom - u_a19_Bathroom >= 0

_C249: u_a19_Bathroom - u_a21_Bathroom >= 0

_C250: u_a21_Bathroom - u_a23_Bathroom >= 0

_C251: u_a23_Bathroom - u_a37_Bathroom >= 0

_C252: - u_a35_Bathroom + u_a37_Bathroom >= 0

_C253: - u_a27_Bathroom + u_a35_Bathroom >= 0

_C254: u_a27_Bathroom - u_a28_Bathroom >= 0

_C255: u_a28_Bathroom - u_a34_Bathroom >= 0

_C256: - u_a24_Bathroom + u_a34_Bathroom >= 0

_C257: u_a1_Car = 1

_C258: u_a6_Car = 0

_C259: u_a1_Car - u_a26_Car >= 0

_C260: u_a26_Car - u_a5_Car >= 0

_C261: - u_a17_Car + u_a5_Car >= 0

_C262: u_a17_Car - u_a33_Car >= 0

_C263: u_a33_Car - u_a34_Car >= 0

_C264: u_a34_Car - u_a49_Car >= 0

_C265: u_a49_Car - u_a7_Car >= 0

_C266: u_a7_Car - u_a9_Car >= 0

_C267: - u_a13_Car + u_a9_Car >= 0

_C268: u_a13_Car - u_a14_Car >= 0

_C269: u_a14_Car - u_a29_Car >= 0

_C270: u_a29_Car - u_a8_Car >= 0

_C271: - u_a21_Car + u_a8_Car >= 0

_C272: u_a21_Car - u_a22_Car >= 0

_C273: u_a22_Car - u_a23_Car >= 0

_C274: u_a23_Car - u_a4_Car >= 0

_C275: - u_a48_Car + u_a4_Car >= 0

_C276: - u_a25_Car + u_a48_Car >= 0

_C277: - u_a16_Car + u_a25_Car >= 0

_C278: - u_a0_Car + u_a16_Car >= 0

_C279: u_a0_Car - u_a40_Car >= 0

_C280: - u_a30_Car + u_a40_Car >= 0

_C281: u_a30_Car - u_a31_Car >= 0

_C282: u_a31_Car - u_a37_Car >= 0

_C283: u_a37_Car - u_a38_Car >= 0

_C284: u_a38_Car - u_a39_Car >= 0

_C285: u_a39_Car - u_a43_Car >= 0

_C286: - u_a10_Car + u_a43_Car >= 0

_C287: u_a10_Car - u_a47_Car >= 0

_C288: - u_a2_Car + u_a47_Car >= 0

_C289: u_a2_Car - u_a3_Car >= 0

_C290: u_a3_Car - u_a46_Car >= 0

_C291: - u_a45_Car + u_a46_Car >= 0

_C292: - u_a44_Car + u_a45_Car >= 0

_C293: - u_a42_Car + u_a44_Car >= 0

_C294: - u_a24_Car + u_a42_Car >= 0

_C295: u_a24_Car - u_a41_Car >= 0

_C296: - u_a27_Car + u_a41_Car >= 0

_C297: - u_a15_Car + u_a27_Car >= 0

_C298: u_a15_Car - u_a18_Car >= 0

_C299: u_a18_Car - u_a19_Car >= 0

_C300: u_a19_Car - u_a20_Car >= 0

_C301: u_a20_Car - u_a36_Car >= 0

_C302: - u_a35_Car + u_a36_Car >= 0

_C303: - u_a32_Car + u_a35_Car >= 0

_C304: - u_a12_Car + u_a32_Car >= 0

_C305: - u_a11_Car + u_a12_Car >= 0

_C306: u_a11_Car - u_a6_Car >= 0

_C307: - u_a28_Car + u_a6_Car >= 0

_C308: u_a19_Landsize = 1

_C309: u_a10_Landsize = 0

_C310: u_a19_Landsize - u_a31_Landsize >= 0

_C311: u_a31_Landsize - u_a49_Landsize >= 0

_C312: - u_a36_Landsize + u_a49_Landsize >= 0

_C313: u_a36_Landsize - u_a48_Landsize >= 0

_C314: - u_a26_Landsize + u_a48_Landsize >= 0

_C315: - u_a16_Landsize + u_a26_Landsize >= 0

_C316: u_a16_Landsize - u_a8_Landsize >= 0

_C317: - u_a5_Landsize + u_a8_Landsize >= 0

_C318: - u_a4_Landsize + u_a5_Landsize >= 0

_C319: u_a4_Landsize - u_a7_Landsize >= 0

_C320: - u_a40_Landsize + u_a7_Landsize >= 0

_C321: - u_a23_Landsize + u_a40_Landsize >= 0

_C322: - u_a21_Landsize + u_a23_Landsize >= 0

_C323: u_a21_Landsize - u_a25_Landsize >= 0

_C324: u_a25_Landsize - u_a29_Landsize >= 0

_C325: - u_a1_Landsize + u_a29_Landsize >= 0

_C326: u_a1_Landsize - u_a38_Landsize >= 0

_C327: - u_a0_Landsize + u_a38_Landsize >= 0

_C328: u_a0_Landsize - u_a37_Landsize >= 0

_C329: - u_a17_Landsize + u_a37_Landsize >= 0

_C330: u_a17_Landsize - u_a39_Landsize >= 0

_C331: - u_a34_Landsize + u_a39_Landsize >= 0

_C332: u_a34_Landsize - u_a41_Landsize >= 0

_C333: u_a41_Landsize - u_a44_Landsize >= 0

_C334: u_a44_Landsize - u_a45_Landsize >= 0

_C335: - u_a18_Landsize + u_a45_Landsize >= 0

_C336: u_a18_Landsize - u_a43_Landsize >= 0

_C337: - u_a3_Landsize + u_a43_Landsize >= 0

_C338: - u_a33_Landsize + u_a3_Landsize >= 0

_C339: - u_a22_Landsize + u_a33_Landsize >= 0

_C340: u_a22_Landsize - u_a35_Landsize >= 0

_C341: - u_a20_Landsize + u_a35_Landsize >= 0

_C342: - u_a11_Landsize + u_a20_Landsize >= 0

_C343: u_a11_Landsize - u_a6_Landsize >= 0

_C344: u_a6_Landsize - u_a9_Landsize >= 0

_C345: - u_a28_Landsize + u_a9_Landsize >= 0

_C346: - u_a13_Landsize + u_a28_Landsize >= 0

_C347: u_a13_Landsize - u_a47_Landsize >= 0

_C348: - u_a32_Landsize + u_a47_Landsize >= 0

_C349: u_a32_Landsize - u_a46_Landsize >= 0

_C350: - u_a24_Landsize + u_a46_Landsize >= 0

_C351: u_a24_Landsize - u_a2_Landsize >= 0

_C352: - u_a12_Landsize + u_a2_Landsize >= 0

_C353: u_a12_Landsize - u_a42_Landsize >= 0

_C354: - u_a30_Landsize + u_a42_Landsize >= 0

_C355: - u_a10_Landsize + u_a30_Landsize >= 0

_C356: u_a10_Landsize - u_a14_Landsize >= 0

_C357: u_a14_Landsize - u_a27_Landsize >= 0

_C358: - u_a15_Landsize + u_a27_Landsize >= 0

_C359: u_a4_BuildingArea = 1

_C360: u_a27_BuildingArea = 0

_C361: - u_a39_BuildingArea + u_a4_BuildingArea >= 0

_C362: - u_a26_BuildingArea + u_a39_BuildingArea >= 0

_C363: - u_a17_BuildingArea + u_a26_BuildingArea >= 0

_C364: - u_a16_BuildingArea + u_a17_BuildingArea >= 0

_C365: u_a16_BuildingArea - u_a25_BuildingArea >= 0

_C366: u_a25_BuildingArea - u_a38_BuildingArea >= 0

_C367: - u_a34_BuildingArea + u_a38_BuildingArea >= 0

_C368: u_a34_BuildingArea - u_a48_BuildingArea >= 0

_C369: - u_a1_BuildingArea + u_a48_BuildingArea >= 0

_C370: u_a1_BuildingArea - u_a49_BuildingArea >= 0

_C371: - u_a41_BuildingArea + u_a49_BuildingArea >= 0

_C372: - u_a36_BuildingArea + u_a41_BuildingArea >= 0

_C373: - u_a23_BuildingArea + u_a36_BuildingArea >= 0

_C374: u_a23_BuildingArea - u_a3_BuildingArea >= 0

_C375: u_a3_BuildingArea - u_a40_BuildingArea >= 0

_C376: u_a40_BuildingArea - u_a44_BuildingArea >= 0

_C377: u_a44_BuildingArea - u_a6_BuildingArea >= 0

_C378: - u_a20_BuildingArea + u_a6_BuildingArea >= 0

_C379: u_a20_BuildingArea - u_a22_BuildingArea >= 0

_C380: u_a22_BuildingArea - u_a31_BuildingArea >= 0

_C381: u_a31_BuildingArea - u_a8_BuildingArea >= 0

_C382: - u_a0_BuildingArea + u_a8_BuildingArea >= 0

_C383: u_a0_BuildingArea - u_a37_BuildingArea >= 0

_C384: - u_a14_BuildingArea + u_a37_BuildingArea >= 0

_C385: u_a14_BuildingArea - u_a24_BuildingArea >= 0

_C386: - u_a18_BuildingArea + u_a24_BuildingArea >= 0

_C387: u_a18_BuildingArea - u_a47_BuildingArea >= 0

_C388: - u_a33_BuildingArea + u_a47_BuildingArea >= 0

_C389: - u_a29_BuildingArea + u_a33_BuildingArea >= 0

_C390: - u_a11_BuildingArea + u_a29_BuildingArea >= 0

_C391: u_a11_BuildingArea - u_a43_BuildingArea >= 0

_C392: u_a43_BuildingArea - u_a45_BuildingArea >= 0

_C393: - u_a30_BuildingArea + u_a45_BuildingArea >= 0

_C394: u_a30_BuildingArea - u_a9_BuildingArea >= 0

_C395: - u_a28_BuildingArea + u_a9_BuildingArea >= 0

_C396: u_a28_BuildingArea - u_a35_BuildingArea >= 0

_C397: u_a35_BuildingArea - u_a5_BuildingArea >= 0

_C398: - u_a12_BuildingArea + u_a5_BuildingArea >= 0

_C399: u_a12_BuildingArea - u_a19_BuildingArea >= 0

_C400: u_a19_BuildingArea - u_a21_BuildingArea >= 0

_C401: u_a21_BuildingArea - u_a7_BuildingArea >= 0

_C402: - u_a13_BuildingArea + u_a7_BuildingArea >= 0

_C403: u_a13_BuildingArea - u_a2_BuildingArea >= 0

_C404: u_a2_BuildingArea - u_a46_BuildingArea >= 0

_C405: - u_a10_BuildingArea + u_a46_BuildingArea >= 0

_C406: u_a10_BuildingArea - u_a32_BuildingArea >= 0

_C407: - u_a15_BuildingArea + u_a32_BuildingArea >= 0

_C408: u_a15_BuildingArea - u_a42_BuildingArea >= 0

_C409: - u_a27_BuildingArea + u_a42_BuildingArea >= 0

_C410: u_a44_YearBuilt = 1

_C411: u_a12_YearBuilt = 0

_C412: - u_a14_YearBuilt + u_a44_YearBuilt >= 0

_C413: u_a14_YearBuilt - u_a20_YearBuilt >= 0

_C414: u_a20_YearBuilt - u_a39_YearBuilt >= 0

_C415: u_a39_YearBuilt - u_a49_YearBuilt >= 0


/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ipykernel_13305/1086142619.py:44: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model += utility_vars[f'u_{df.index[sorted_alts[j]]}_{df.columns[i]}'] >= utility_vars[f'u_{df.index[sorted_alts[j+1]]}_{df.columns[i]}']
/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ipykernel_13305/1086142619.py:44: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model += utility_vars[f'u_{df.index[sorted_alts[j]]}_{df.columns[i]}'] >= utility_vars[f'u_{df.index[sorted_alts[j+1]]}_{df.columns[i]}']
/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ipykernel_13305/1086142619.py:44: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model += utility_vars[f'u_{df.index[sorted_alts[j]]}_{df.columns[i]}'] >= utility_vars[f'u_{df.index[sorted_alts[j+1]]}_{df.columns[i]}']
/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ipykernel_13305/1086142619.py:44: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model += utility_vars[f'u_{df.index[sorted_alts[j]]}_{df.columns[i]}'] >= utility_vars[f'u_{df.index[sorted_alts[j+1]]}_{df.columns[i]}']
/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ipykernel_13305/1086142619.py:44: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model += utility_vars[f'u_{df.index[sorted_alts[j]]}_{df.columns[i]}'] >= utility_vars[f'u_{df.index[sorted_alts[j+1]]}_{df.columns[i]}']
/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ipykernel_13305/1086142619.py:44: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model += utility_vars[f'u_{df.index[sorted_alts[j]]}_{df.columns[i]}'] >= utility_vars[f'u_{df.index[sorted_alts[j+1]]}_{df.columns[i]}']
/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ipykernel_13305/1086142619.py:44: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model += utility_vars[f'u_{df.index[sorted_alts[j]]}_{df.columns[i]}'] >= utility_vars[f'u_{df.index[sorted_alts[j+1]]}_{df.columns[i]}']
/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ipykernel_13305/1086142619.py:44: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model += utility_vars[f'u_{df.index[sorted_alts[j]]}_{df.columns[i]}'] >= utility_vars[f'u_{df.index[sorted_alts[j+1]]}_{df.columns[i]}']
/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ipykernel_13305/1086142619.py:44: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model += utility_vars[f'u_{df.index[sorted_alts[j]]}_{df.columns[i]}'] >= utility_vars[f'u_{df.index[sorted_alts[j+1]]}_{df.columns[i]}']

TypeError: must be real number, not ellipsis